### ISSUE TITLE
when I run run_test.py, CUDA out of memory

### ISSUE THREAD

**Issue by Foolssss** [TencentYoutuResearch/CrowdCounting-P2PNet#30]
RuntimeError: CUDA out of memory. Tried to allocate 88.00 MiB (GPU 0; 8.00 GiB total capacity; 6.17 GiB already allocated; 63.69 MiB free; 6.23 GiB reserved in total by PyTorch)

**Comment by conan-CV** [comment]
我也刚运行了run_test.py，是没有问题的

**Comment by Foolssss** [comment]
> 我也刚运行了run_test.py，是没有问题的

你测试的图像是多大尺寸的，测试了几张图像？

**Comment by Mukilan-Mohanachandran** [comment]
hi  @fyh-cumtb , I encountered the same problem. later I found this is because of the image size. my image was in 4k res, I converted it into the size of demo1.jpg 's size (available under this repository's vis directory) using cv2.resize(), now it's working for me.
